kind: Service
apiVersion: v1
metadata:
  name: rollout-stable
spec:
  selector:
    app: rollout-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  
---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary
spec:
  selector:
    app: rollout-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080